# Generated by Django 5.1.6 on 2025-02-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_groups_group_rename_stundents_stundent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stundent',
            new_name='Student',
        ),
    ]
