# Generated by Django 5.1.6 on 2025-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_stundent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_headman',
            field=models.BooleanField(default=False),
        ),
    ]
